// Mock Data Types
export interface MockProduct {
  id: number;
  name: string;
  price: number;
  category: string;
  categoryName: string;
  image: string;
  description: string;
  rating: number;
  inStock: boolean;
  [key: string]: any; // For additional properties
}

export interface MockCategory {
  value: string;
  label: string;
}

// Boxes Mock Data
export const boxCategories: MockCategory[] = [
  { value: "all", label: "Tất Cả Hộp" },
  { value: "paper", label: "Hộp Giấy" },
  { value: "wood", label: "Hộp Gỗ" },
  { value: "plastic", label: "Hộp Nhựa" },
  { value: "metal", label: "Hộp Kim Loại" },
  { value: "eco", label: "Hộp Thân Thiện Môi Trường" },
];

export const boxes: MockProduct[] = [
  {
    id: 1,
    name: "Hộp Giấy Kraft Eco",
    price: 25000,
    category: "eco",
    categoryName: "Hộp Thân Thiện Môi Trường",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp giấy kraft tái chế, thân thiện môi trường",
    material: "Giấy kraft",
    size: "12cm x 12cm x 8cm",
    rating: 4.5,
    inStock: true,
    capacity: "1 nến",
  },
  {
    id: 2,
    name: "Hộp Gỗ Tre Cao Cấp",
    price: 85000,
    category: "wood",
    categoryName: "Hộp Gỗ",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp gỗ tre tự nhiên, sang trọng và bền đẹp",
    material: "Gỗ tre",
    size: "15cm x 15cm x 10cm",
    rating: 4.8,
    inStock: true,
    capacity: "2 nến",
  },
  {
    id: 3,
    name: "Hộp Nhựa Trong Suốt",
    price: 35000,
    category: "plastic",
    categoryName: "Hộp Nhựa",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp nhựa trong suốt, bảo vệ và trưng bày sản phẩm",
    material: "Nhựa PET",
    size: "10cm x 10cm x 8cm",
    rating: 4.2,
    inStock: true,
    capacity: "1 nến",
  },
  {
    id: 4,
    name: "Hộp Giấy Cao Cấp",
    price: 45000,
    category: "paper",
    categoryName: "Hộp Giấy",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp giấy cao cấp với thiết kế sang trọng",
    material: "Giấy duplex",
    size: "14cm x 14cm x 9cm",
    rating: 4.6,
    inStock: true,
    capacity: "1-2 nến",
  },
  {
    id: 5,
    name: "Hộp Kim Loại Vintage",
    price: 120000,
    category: "metal",
    categoryName: "Hộp Kim Loại",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp kim loại phong cách vintage, có thể tái sử dụng",
    material: "Thiếc",
    size: "16cm x 12cm x 8cm",
    rating: 4.9,
    inStock: false,
  },
  {
    id: 6,
    name: "Hộp Giấy Hoa Văn",
    price: 38000,
    category: "paper",
    categoryName: "Hộp Giấy",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp giấy với họa tiết hoa văn đẹp mắt",
    material: "Giấy art",
    size: "13cm x 13cm x 8cm",
    rating: 4.4,
    inStock: true,
    capacity: "1 nến",
  },
  {
    id: 7,
    name: "Hộp Tre Tròn",
    price: 65000,
    category: "eco",
    categoryName: "Hộp Thân Thiện Môi Trường",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp tre tròn tự nhiên, độc đáo",
    material: "Tre tự nhiên",
    size: "Đường kính 12cm x 8cm",
    rating: 4.7,
    inStock: true,
    capacity: "1 nến",
  },
  {
    id: 8,
    name: "Hộp Nhựa Màu Sắc",
    price: 42000,
    category: "plastic",
    categoryName: "Hộp Nhựa",
    image: "/placeholder.svg?height=250&width=250",
    description: "Hộp nhựa nhiều màu sắc, bắt mắt",
    material: "Nhựa PP",
    size: "11cm x 11cm x 7cm",
    rating: 4.1,
    inStock: true,
    capacity: "1 nến",
  },
];

// Cards Mock Data
export const cardCategories: MockCategory[] = [
  { value: "all", label: "Tất Cả Thiệp" },
  { value: "birthday", label: "Sinh Nhật" },
  { value: "thank-you", label: "Cảm Ơn" },
  { value: "congratulations", label: "Chúc Mừng" },
  { value: "love", label: "Tình Yêu" },
  { value: "holiday", label: "Ngày Lễ" },
];

export const cards: MockProduct[] = [
  {
    id: 1,
    name: "Thiệp Sinh Nhật Hoa Tươi",
    price: 15000,
    category: "birthday",
    categoryName: "Sinh Nhật",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp sinh nhật với họa tiết hoa tươi đẹp mắt",
    material: "Giấy cao cấp",
    size: "15cm x 10cm",
    rating: 4.6,
    inStock: true,
    design: "Hoa tươi",
  },
  {
    id: 2,
    name: "Thiệp Cảm Ơn Tối Giản",
    price: 12000,
    category: "thank-you",
    categoryName: "Cảm Ơn",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp cảm ơn thiết kế tối giản, thanh lịch",
    material: "Giấy kraft",
    size: "14cm x 9cm",
    rating: 4.4,
    inStock: true,
    design: "Tối giản",
  },
  {
    id: 3,
    name: "Thiệp Chúc Mừng Vàng Kim",
    price: 20000,
    category: "congratulations",
    categoryName: "Chúc Mừng",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp chúc mừng với chi tiết vàng kim sang trọng",
    material: "Giấy art",
    size: "16cm x 11cm",
    rating: 4.8,
    inStock: true,
    design: "Vàng kim",
  },
  {
    id: 4,
    name: "Thiệp Tình Yêu Trái Tim",
    price: 18000,
    category: "love",
    categoryName: "Tình Yêu",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp tình yêu với họa tiết trái tim lãng mạn",
    material: "Giấy cao cấp",
    size: "15cm x 10cm",
    rating: 4.7,
    inStock: true,
    design: "Trái tim",
  },
  {
    id: 5,
    name: "Thiệp Giáng Sinh Cây Thông",
    price: 22000,
    category: "holiday",
    categoryName: "Ngày Lễ",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp Giáng sinh với hình cây thông đẹp mắt",
    material: "Giấy cao cấp",
    size: "17cm x 12cm",
    rating: 4.9,
    inStock: false,
  },
  {
    id: 6,
    name: "Thiệp Sinh Nhật Động Vật",
    price: 16000,
    category: "birthday",
    categoryName: "Sinh Nhật",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp sinh nhật với hình động vật dễ thương",
    material: "Giấy cao cấp",
    size: "15cm x 10cm",
    rating: 4.5,
    inStock: true,
    design: "Động vật",
  },
  {
    id: 7,
    name: "Thiệp Cảm Ơn Hoa Lavender",
    price: 14000,
    category: "thank-you",
    categoryName: "Cảm Ơn",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp cảm ơn với họa tiết hoa lavender thư giãn",
    material: "Giấy kraft",
    size: "14cm x 9cm",
    rating: 4.6,
    inStock: true,
    design: "Hoa lavender",
  },
  {
    id: 8,
    name: "Thiệp Năm Mới Pháo Hoa",
    price: 25000,
    category: "holiday",
    categoryName: "Ngày Lễ",
    image: "/placeholder.svg?height=250&width=250",
    description: "Thiệp năm mới với họa tiết pháo hoa rực rỡ",
    material: "Giấy art",
    size: "18cm x 13cm",
    rating: 4.8,
    inStock: true,
    design: "Pháo hoa",
  },
];

// Molds Mock Data
export const moldCategories: MockCategory[] = [
  { value: "all", label: "Tất Cả Khuôn" },
  { value: "basic", label: "Khuôn Cơ Bản" },
  { value: "decorative", label: "Khuôn Trang Trí" },
  { value: "seasonal", label: "Khuôn Theo Mùa" },
  { value: "custom", label: "Khuôn Tùy Chỉnh" },
];

export const molds: MockProduct[] = [
  {
    id: 1,
    name: "Khuôn Tròn Cơ Bản",
    price: 65000,
    category: "basic",
    categoryName: "Khuôn Cơ Bản",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn silicon tròn cơ bản, phù hợp cho người mới bắt đầu",
    material: "Silicon cao cấp",
    size: "Đường kính 8cm",
    rating: 4.3,
    inStock: true,
    capacity: "100ml",
  },
  {
    id: 2,
    name: "Khuôn Trái Tim Lãng Mạn",
    price: 85000,
    category: "decorative",
    categoryName: "Khuôn Trang Trí",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn trái tim với chi tiết tinh tế, lãng mạn",
    material: "Silicon cao cấp",
    size: "10cm x 8cm",
    rating: 4.7,
    inStock: true,
    capacity: "120ml",
  },
  {
    id: 3,
    name: "Khuôn Hoa Hồng",
    price: 95000,
    category: "decorative",
    categoryName: "Khuôn Trang Trí",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn hoa hồng với cánh hoa chi tiết",
    material: "Silicon cao cấp",
    size: "12cm x 12cm",
    rating: 4.8,
    inStock: true,
    capacity: "150ml",
  },
  {
    id: 4,
    name: "Khuôn Giáng Sinh",
    price: 75000,
    category: "seasonal",
    categoryName: "Khuôn Theo Mùa",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn cây thông Giáng sinh đẹp mắt",
    material: "Silicon cao cấp",
    size: "15cm x 10cm",
    rating: 4.6,
    inStock: true,
    capacity: "200ml",
  },
  {
    id: 5,
    name: "Khuôn Vuông Hiện Đại",
    price: 70000,
    category: "basic",
    categoryName: "Khuôn Cơ Bản",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn vuông với góc cạnh hiện đại",
    material: "Silicon cao cấp",
    size: "10cm x 10cm",
    rating: 4.4,
    inStock: true,
    capacity: "100ml",
  },
  {
    id: 6,
    name: "Khuôn Bướm Xinh",
    price: 90000,
    category: "decorative",
    categoryName: "Khuôn Trang Trí",
    image: "/placeholder.svg?height=250&width=250",
    description: "Khuôn bướm với cánh mỏng manh",
    material: "Silicon cao cấp",
    size: "14cm x 12cm",
    rating: 4.9,
    inStock: false,
  },
];

// Scents Mock Data
export const scentCategories: MockCategory[] = [
  { value: "all", label: "Tất Cả Mùi Hương" },
  { value: "floral", label: "Hoa" },
  { value: "fruity", label: "Trái Cây" },
  { value: "woody", label: "Gỗ" },
  { value: "fresh", label: "Tươi Mát" },
  { value: "spicy", label: "Gia Vị" },
];

export const scents: MockProduct[] = [
  {
    id: 1,
    name: "Tinh Dầu Lavender",
    price: 85000,
    category: "floral",
    categoryName: "Hoa",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu lavender thư giãn, giúp ngủ ngon",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.8,
    inStock: true,
    intensity: "Trung bình",
  },
  {
    id: 2,
    name: "Tinh Dầu Vanilla",
    price: 75000,
    category: "fruity",
    categoryName: "Trái Cây",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu vanilla ngọt ngào, ấm áp",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.6,
    inStock: true,
    intensity: "Mạnh",
  },
  {
    id: 3,
    name: "Tinh Dầu Gỗ Đàn Hương",
    price: 95000,
    category: "woody",
    categoryName: "Gỗ",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu gỗ đàn hương sang trọng, nam tính",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.9,
    inStock: true,
    intensity: "Mạnh",
  },
  {
    id: 4,
    name: "Tinh Dầu Bạc Hà",
    price: 65000,
    category: "fresh",
    categoryName: "Tươi Mát",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu bạc hà tươi mát, sảng khoái",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.5,
    inStock: true,
    intensity: "Mạnh",
  },
  {
    id: 5,
    name: "Tinh Dầu Hoa Hồng",
    price: 120000,
    category: "floral",
    categoryName: "Hoa",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu hoa hồng lãng mạn, nữ tính",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.7,
    inStock: true,
    intensity: "Trung bình",
  },
  {
    id: 6,
    name: "Tinh Dầu Quế",
    price: 80000,
    category: "spicy",
    categoryName: "Gia Vị",
    image: "/placeholder.svg?height=250&width=250",
    description: "Tinh dầu quế ấm áp, kích thích",
    material: "Tinh dầu tự nhiên",
    volume: "10ml",
    rating: 4.4,
    inStock: false,
  },
];

// Colors Mock Data
export const colorCategories: MockCategory[] = [
  { value: "all", label: "Tất Cả Màu" },
  { value: "warm", label: "Màu Ấm" },
  { value: "cool", label: "Màu Lạnh" },
  { value: "neutral", label: "Màu Trung Tính" },
  { value: "bright", label: "Màu Sáng" },
  { value: "pastel", label: "Màu Pastel" },
];

export const colors: MockProduct[] = [
  {
    id: 1,
    name: "Màu Đỏ Tươi",
    price: 25000,
    category: "warm",
    categoryName: "Màu Ấm",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu đỏ tươi nổi bật, phù hợp cho dịp đặc biệt",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.5,
    inStock: true,
    intensity: "Mạnh",
  },
  {
    id: 2,
    name: "Màu Xanh Dương",
    price: 25000,
    category: "cool",
    categoryName: "Màu Lạnh",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu xanh dương thư giãn, mát mẻ",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.3,
    inStock: true,
    intensity: "Trung bình",
  },
  {
    id: 3,
    name: "Màu Vàng Kim",
    price: 30000,
    category: "bright",
    categoryName: "Màu Sáng",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu vàng kim sang trọng, nổi bật",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.7,
    inStock: true,
    intensity: "Mạnh",
  },
  {
    id: 4,
    name: "Màu Hồng Pastel",
    price: 22000,
    category: "pastel",
    categoryName: "Màu Pastel",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu hồng pastel dịu mắt, nữ tính",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.6,
    inStock: true,
    intensity: "Nhẹ",
  },
  {
    id: 5,
    name: "Màu Xanh Lá",
    price: 25000,
    category: "cool",
    categoryName: "Màu Lạnh",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu xanh lá tự nhiên, thư giãn",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.4,
    inStock: true,
    intensity: "Trung bình",
  },
  {
    id: 6,
    name: "Màu Tím Lavender",
    price: 28000,
    category: "pastel",
    categoryName: "Màu Pastel",
    image: "/placeholder.svg?height=250&width=250",
    description: "Màu tím lavender lãng mạn, thư giãn",
    material: "Bột màu an toàn",
    weight: "50g",
    rating: 4.8,
    inStock: false,
  },
]; 